<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja_JP">
<context>
    <name>MainWindow</name>
    <message>
        <location filename="src/lite/mainwindow.py" line="30"/>
        <source>Excel (*.xlsx *.xlsm);;CSV (*.csv)</source>
        <translation></translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="31"/>
        <source>Excel (*.xlsx)</source>
        <translation></translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="35"/>
        <source>surveytool</source>
        <translation>アンケート集計ツール</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="114"/>
        <source>TOTAL</source>
        <translation>総数</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="115"/>
        <source>BLANK</source>
        <translation>無回答</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="198"/>
        <source>Error: config load failed.</source>
        <translation>エラー：設定もしくはソースの読み込みに失敗しました。</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="200"/>
        <source>Error: output file path is not directory.</source>
        <translation>エラー：出力パスがフォルダではありません。</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="181"/>
        <source>simple.xlsx</source>
        <translation>単純集計.xlsx</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="204"/>
        <source>cross.xlsx</source>
        <translation>クロス集計.xlsx</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="218"/>
        <source>loading...</source>
        <translation>読み込み中…</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="221"/>
        <source>Error: Input &quot;%1&quot; not found.</source>
        <translation>エラー： 入力 &quot;%1&quot; が見つかりません。</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="224"/>
        <source>Input: &quot;%1&quot;</source>
        <translation>入力： &quot;%1&quot;</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="232"/>
        <source>Error: Input &quot;%1&quot; load failed.</source>
        <translation>エラー：入力 &quot;%1&quot; の読み込みに失敗しました。</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="263"/>
        <source>validating...</source>
        <translation>検証中…</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="316"/>
        <source>Finished</source>
        <translation>完了</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="316"/>
        <source>Finished.</source>
        <translation>完了しました。</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="318"/>
        <source>Error</source>
        <translation>エラー</translation>
    </message>
    <message>
        <location filename="src/lite/mainwindow.py" line="318"/>
        <source>Write error.</source>
        <translation>書き込みに失敗しました。</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="14"/>
        <source>MainWindow</source>
        <translation></translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="102"/>
        <source>...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="95"/>
        <source>Input</source>
        <translation>入力</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="48"/>
        <source>Drop N/A</source>
        <translation>無回答を除く</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="55"/>
        <source>Cross</source>
        <translation>クロス集計</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="116"/>
        <source>Output</source>
        <translation>出力</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="123"/>
        <source>Simple</source>
        <translation>単純集計</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="25"/>
        <source>Menu</source>
        <translation>メニュー</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="131"/>
        <source>Message</source>
        <translation>メッセージ</translation>
    </message>
    <message>
        <location filename="src/lite/ui_mainwindow.ui" line="146"/>
        <source>Exit</source>
        <translation>終了</translation>
    </message>
</context>
<context>
    <name>QValidationObject</name>
    <message>
        <location filename="src/qvalidator.py" line="38"/>
        <source>Warning: Column &quot;%1&quot; is not found.</source>
        <translation>警告： &quot;%1&quot;列が見つかりません。</translation>
    </message>
    <message>
        <location filename="src/qvalidator.py" line="44"/>
        <source>Warning: Setting &quot;%1&quot; is not found.</source>
        <translation>警告： 設定 &quot;%1&quot; が見つかりません。</translation>
    </message>
    <message>
        <location filename="src/qvalidator.py" line="50"/>
        <source>Warning: Setting &quot;%1&quot; is Unknown type.</source>
        <translation>警告： 設定 &quot;%1&quot; は未定義です。</translation>
    </message>
    <message>
        <location filename="src/qvalidator.py" line="56"/>
        <source>Warning: Undefined value found in &quot;%1&quot; - #%2 : &apos;%3&apos;</source>
        <translation>警告： 未定義の値 &quot;%3&quot; が見つかりました。 位置： &quot;%1&quot; - ID:%2</translation>
    </message>
    <message>
        <location filename="src/qvalidator.py" line="64"/>
        <source>Warning: It exceeds the limit value was found in &quot;%1&quot; - #%2 : &apos;%3&apos;</source>
        <translation>警告：制限を超えた値が見つかりました。 位置： &quot;%1&quot; - ID:%2 値：&apos;%3&apos;</translation>
    </message>
</context>
<context>
    <name>SimpleAggregationObject</name>
    <message>
        <location filename="src/lite/mainwindow.py" line="342"/>
        <source>SimpleAggregation</source>
        <translation>単純集計</translation>
    </message>
</context>
</TS>
